/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.servicename.ifname.xml -p sample_interface -a sample_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SAMPLE_ADAPTOR_H_1447501139
#define SAMPLE_ADAPTOR_H_1447501139

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.servicename.ifname
 */
class IfnameAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.servicename.ifname")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.servicename.ifname\">\n"
"    <signal name=\"syncSend\">\n"
"      <arg direction=\"out\" type=\"ay\" name=\"data\"/>\n"
"    </signal>\n"
"    <method name=\"asyncInvoke\">\n"
"      <arg direction=\"in\" type=\"ay\" name=\"data\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    IfnameAdaptor(QObject *parent);
    virtual ~IfnameAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString asyncInvoke(const QByteArray &data);
Q_SIGNALS: // SIGNALS
    void syncSend(const QByteArray &data);
};

#endif
