/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.servicename.ifname.xml -p sample_interface -a sample_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "sample_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class IfnameAdaptor
 */

IfnameAdaptor::IfnameAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

IfnameAdaptor::~IfnameAdaptor()
{
    // destructor
}

QString IfnameAdaptor::asyncInvoke(const QByteArray &data)
{
    // handle method call com.servicename.ifname.asyncInvoke
    QString out0;
    QMetaObject::invokeMethod(parent(), "asyncInvoke", Q_RETURN_ARG(QString, out0), Q_ARG(QByteArray, data));
    return out0;
}

